# Generated by Django 3.2.4 on 2021-06-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_id',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacture_id',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_id',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
